# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build & publish
      env:
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        ls -l
        echo 'Docker login'
        docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
        echo 'Running build...'
        docker build -t bkalinovski/testrepo:latest ./src/TestApplication/.
        echo 'Pusing image...'
        docker push bkalinovski/testrepo:latest
        echo 'Done!'
        
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: deploy on DigitalOcean droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_LOGIN }}
          password: ${{ secrets.DIGITAL_OCEAN_PASSWORD }}
          script: bash scripts/updateTestRepo.sh
    
