name: Telegram

on:
  issues:
    types: [assigned]

jobs:
  sendmessage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: You were assigned to issue ${{ github.event.inputs.name }}
