name: Telegram

on:
  issues:
    types: [assigned]

jobs:
  consolelog:
     runs-on: ubuntu-latest
     steps:
     - name: Show GitHub context   
       env: 
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_ACTOR: ${{ github.actor }}
        ASSIGNEES: ${{ github.event.assignee.login }}
       run: |
        echo "$GITHUB_CONTEXT"
        echo "Actor $GITHUB_ACTOR"
        echo "Assignees $ASSIGNEES"

  sendmessage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET
      env: 
        ISSUE_TITLE: ${{ github.event.issue.title }}
        GITHUB_ACTOR: ${{ github.actor }}
        ISSUE_ASSIGNEE: ${{ github.event.issue.assignee.login }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.event.issue.assignee.login }} was assigned to issue: ${{ github.event.issue.title }}
          Body:
          ```${{ github.event.issue.body }}```
